### ISSUE TITLE
Wrong json example causes malfunction

### ISSUE THREAD

**Issue by mikaelivarsson** [cboddy/i3-workspace-names-daemon#35] opened 2020-07-09 19:50 UTC
In the json example the last comma (',') has to be removed, otherwise the app won't work properly (icons won't show).
It took some time for me to figure this out and I think it is a good idea if the example can be corrected to avoid more confusion to others.

**Comment by CastixGitHub** [comment] 2020-07-09 21:58
duplicate of #34 
@cboddy are you there?

**Comment by cboddy** [comment] 2020-07-10 13:02
Hi both, 

Thanks for reporting, this is now fixed in  the README. I've also added an example to validate your config-file.

**Closed as completed by cboddy** 2020-07-10 13:02 UTC
